### ISSUE TITLE
poetry update fails on Python >= 3.9

### ISSUE THREAD

**Issue by timw** [fedej/poetry-grpc-plugin#2]
When running `poetry update` in a build environment using Python >= 3.9, it fails with an error:

```
   3  .venv/lib/python3.9/site-packages/poetry_grpc_plugin/plugins.py:27 in run_protoc
        with importlib.resources.path("grpc_tools", "_proto") as include_path:

   2  /usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py:119 in __enter__
        return next(self.gen)

   1  /usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/resources.py:175 in _path_from_reader
        opener_reader = reader.open_resource(norm_resource)

  IsADirectoryError

  [Errno 21] Is a directory: '<snip>/.venv/lib/python3.9/site-packages/grpc_tools/_proto'

  at <frozen importlib._bootstrap_external>:1055 in open_resource
```

It appears that the behaviour of `importlib.resources.path` has been tightened in 3.9 to work only on files.

I've personally used `pkg_resources.resource_filename` in Python 3.9 to achieve this exact lookup, so that could be an alternative.

Related links:
 - https://www.mail-archive.com/python-bugs-list@python.org/msg451088.html
 -  https://github.com/ktbyers/netmiko/issues/2048 
 - https://github.com/ktbyers/netmiko/pull/2274

**Comment by fedej** [comment]
Thanks for raising this, I've released 0.1.1 addressing this issue.
