### ISSUE TITLE
New release needed

### ISSUE THREAD

**Issue by ghost** [fedej/poetry-grpc-plugin#21]
The `protobuf` python package introduced breaking changes between version `3.20.3` and version `4.21.1` (https://pypi.org/project/protobuf/#history).
`grpc_tools` pulled in these changes on version `1.49.0` (https://github.com/grpc/grpc/commit/41ec08c69a9d298015cb44316c445d58ad0b2e9c).
The current version (`0.1.3`) of `poetry-grpc-plugin` pins `mypy-protobuf` to `^2.9`, which is incompatible with the breaking changes introduced by `protobuf`:

    TypeError: Descriptors cannot not be created directly.
    If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
    If you cannot immediately regenerate your protos, some other possible workarounds are:
     1. Downgrade the protobuf package to 3.20.x or lower.
     2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
    
    More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

The version pinning of `mypy-protobuf` is already fixed with abcb5d05221d7f1dd68659c51a61274a4ef9adc5, but needs to be released.

**Comment by fedej** [comment]
Released version 0.1.4 just now
