### ISSUE TITLE
Incompatible with latest (1.4) version of Poetry

### ISSUE THREAD

**Issue by hozn** [fedej/poetry-grpc-plugin#29]
Obviously this was deliberate, though it threw a wrench in our build, since Poetry wants you to use their curl-based installer script (so it always grabs the latest).  We've worked around it by having poetry downgrade itself before install, but would love to be on the latest version.

```
#0 1.390 Using version ^0.1.5 for poetry-grpc-plugin
#0 1.395
#0 1.442 Updating dependencies
#0 1.444 Resolving dependencies...
#0 1.533
#0 1.533 Because no versions of poetry-grpc-plugin match >0.1.5,<0.2.0
#0 1.533  and poetry-grpc-plugin (0.1.5) depends on poetry (>=1.2.0,<1.4), poetry-grpc-plugin (>=0.1.5,<0.2.0) requires poetry (>=1.2.0,<1.4).
#0 1.533 So, because poetry-instance depends on both poetry (1.4.0) and poetry-grpc-plugin (^0.1.5), version solving failed.
```

**Comment by theirix** [comment]
Could you please merge a Dependabot PR #34 ? It fully resolves the problem. Checked at my local installation with 1.4.1.

**Comment by theirix** [comment]
I found the GitHub release 0.1.6 but not on PyPi, can you push it too?

**Comment by fedej** [comment]
I'll try to get to it this weekend, the workflow is currently broken. Contributions are also welcome

**Comment by fedej** [comment]
New release has been published, let me know if you still have issues
